QT.gui_private.VERSION = 5.12.8
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.12.8 $$QT_MODULE_INCLUDE_BASE/QtGui/5.12.8/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.uses =
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = xkbcommon xcb accessibility-atspi-bridge drm_atomic egl egl_x11 eglfs kms eglfs_egldevice eglfs_gbm xlib xcb-xlib eglfs_x11 evdev freetype system-freetype fontconfig gif harfbuzz ico jpeg libinput libinput-axis-api linuxfb mtdev multiprocess png system-harfbuzz system-jpeg system-png system-xcb tuiotouch vnc xcb-egl-plugin xcb-native-painting xcb-sm xcb-xinput xkb xrender
QT.gui_private.disabled_features = dxguid angle_d3d11_qdtd direct2d direct2d1_1 dxgi direct3d11 direct3d11_1 direct3d9 directfb dxgi1_2 eglfs_brcm eglfs_mali eglfs_openwfd eglfs_rcar eglfs_viv eglfs_viv_wl vsp2 eglfs_vsp2 integrityfb integrityhid mirclient texture_format_astc_experimental tslib xcb-glx-plugin
QMAKE_LIBS_XKBCOMMON = /usr/lib/arm-linux-gnueabihf/libxkbcommon.so
QMAKE_LIBS_XCB = /usr/lib/arm-linux-gnueabihf/libxcb.so
QMAKE_LIBS_ATSPI = /usr/lib/arm-linux-gnueabihf/libatspi.so /usr/lib/arm-linux-gnueabihf/libdbus-1.so /usr/lib/arm-linux-gnueabihf/libglib-2.0.so
QMAKE_INCDIR_ATSPI = /usr/include/at-spi-2.0 /usr/include/dbus-1.0 /usr/lib/arm-linux-gnueabihf/dbus-1.0/include /usr/include/glib-2.0 /usr/lib/arm-linux-gnueabihf/glib-2.0/include
QMAKE_LIBS_OPENGL_ES2 = /usr/lib/arm-linux-gnueabihf/libGLESv2.so
QMAKE_INCDIR_OPENGL_ES2 = 
QMAKE_LIBS_DRM = /usr/lib/arm-linux-gnueabihf/libdrm.so
QMAKE_INCDIR_DRM = /usr/include/libdrm
QMAKE_LIBS_EGL = /usr/lib/arm-linux-gnueabihf/libEGL.so
QMAKE_INCDIR_EGL = 
QMAKE_LIBS_XLIB = /usr/lib/arm-linux-gnueabihf/libXext.so /usr/lib/arm-linux-gnueabihf/libX11.so /usr/lib/arm-linux-gnueabihf/libm.so
QMAKE_LIBS_GBM = /usr/lib/arm-linux-gnueabihf/libgbm.so
QMAKE_DEPENDS_XCB_XLIB_CC = XCB XLIB
QMAKE_DEPENDS_XCB_XLIB_LD = XCB XLIB
QMAKE_LIBS_XCB_XLIB = /usr/lib/arm-linux-gnueabihf/libX11-xcb.so
QMAKE_DEPENDS_FREETYPE_CC = ZLIB
QMAKE_DEPENDS_FREETYPE_LD = ZLIB
QMAKE_LIBS_FREETYPE = /usr/lib/arm-linux-gnueabihf/libfreetype.so
QMAKE_INCDIR_FREETYPE = /usr/include/freetype2 /usr/include/libpng16
QMAKE_DEPENDS_FONTCONFIG_CC = FREETYPE
QMAKE_DEPENDS_FONTCONFIG_LD = FREETYPE
QMAKE_LIBS_FONTCONFIG = /usr/lib/arm-linux-gnueabihf/libfontconfig.so
QMAKE_INCDIR_FONTCONFIG = /usr/include/uuid
QMAKE_LIBS_LIBINPUT = /usr/lib/arm-linux-gnueabihf/libinput.so
QMAKE_LIBS_MTDEV = /usr/lib/arm-linux-gnueabihf/libmtdev.so
QMAKE_LIBS_HARFBUZZ = /usr/lib/arm-linux-gnueabihf/libharfbuzz.so
QMAKE_LIBS_LIBJPEG = /usr/lib/arm-linux-gnueabihf/libjpeg.so
QMAKE_DEPENDS_LIBPNG_CC = ZLIB
QMAKE_DEPENDS_LIBPNG_LD = ZLIB
QMAKE_LIBS_LIBPNG = /usr/lib/arm-linux-gnueabihf/libpng16.so
QMAKE_INCDIR_LIBPNG = /usr/include/libpng16
QMAKE_DEPENDS_XCB_ICCCM_CC = XCB
QMAKE_DEPENDS_XCB_ICCCM_LD = XCB
QMAKE_LIBS_XCB_ICCCM = /usr/lib/arm-linux-gnueabihf/libxcb-icccm.so
QMAKE_DEPENDS_XCB_SHM_CC = XCB
QMAKE_DEPENDS_XCB_SHM_LD = XCB
QMAKE_LIBS_XCB_SHM = /usr/lib/arm-linux-gnueabihf/libxcb-shm.so
QMAKE_DEPENDS_XCB_IMAGE_CC = XCB_SHM XCB
QMAKE_DEPENDS_XCB_IMAGE_LD = XCB_SHM XCB
QMAKE_LIBS_XCB_IMAGE = /usr/lib/arm-linux-gnueabihf/libxcb-image.so
QMAKE_DEPENDS_XCB_KEYSYMS_CC = XCB
QMAKE_DEPENDS_XCB_KEYSYMS_LD = XCB
QMAKE_LIBS_XCB_KEYSYMS = /usr/lib/arm-linux-gnueabihf/libxcb-keysyms.so
QMAKE_DEPENDS_XCB_RANDR_CC = XCB
QMAKE_DEPENDS_XCB_RANDR_LD = XCB
QMAKE_LIBS_XCB_RANDR = /usr/lib/arm-linux-gnueabihf/libxcb-randr.so
QMAKE_DEPENDS_XCB_RENDER_CC = XCB
QMAKE_DEPENDS_XCB_RENDER_LD = XCB
QMAKE_LIBS_XCB_RENDER = /usr/lib/arm-linux-gnueabihf/libxcb-render.so
QMAKE_DEPENDS_XCB_RENDERUTIL_CC = XCB XCB_RENDER
QMAKE_DEPENDS_XCB_RENDERUTIL_LD = XCB XCB_RENDER
QMAKE_LIBS_XCB_RENDERUTIL = /usr/lib/arm-linux-gnueabihf/libxcb-render-util.so
QMAKE_DEPENDS_XCB_SHAPE_CC = XCB
QMAKE_DEPENDS_XCB_SHAPE_LD = XCB
QMAKE_LIBS_XCB_SHAPE = /usr/lib/arm-linux-gnueabihf/libxcb-shape.so
QMAKE_DEPENDS_XCB_SYNC_CC = XCB
QMAKE_DEPENDS_XCB_SYNC_LD = XCB
QMAKE_LIBS_XCB_SYNC = /usr/lib/arm-linux-gnueabihf/libxcb-sync.so
QMAKE_DEPENDS_XCB_XFIXES_CC = XCB
QMAKE_DEPENDS_XCB_XFIXES_LD = XCB
QMAKE_LIBS_XCB_XFIXES = /usr/lib/arm-linux-gnueabihf/libxcb-xfixes.so
QMAKE_DEPENDS_XCB_XINERAMA_CC = XCB
QMAKE_DEPENDS_XCB_XINERAMA_LD = XCB
QMAKE_LIBS_XCB_XINERAMA = /usr/lib/arm-linux-gnueabihf/libxcb-xinerama.so
QMAKE_LIBS_VULKAN = /usr/lib/arm-linux-gnueabihf/libvulkan.so
QMAKE_DEPENDS_XRENDER_CC = XLIB
QMAKE_DEPENDS_XRENDER_LD = XLIB
QMAKE_LIBS_XRENDER = /usr/lib/arm-linux-gnueabihf/libXrender.so
QMAKE_LIBS_X11SM = /usr/lib/arm-linux-gnueabihf/libSM.so /usr/lib/arm-linux-gnueabihf/libICE.so
QMAKE_DEPENDS_XCB_XINPUT_CC = XCB
QMAKE_DEPENDS_XCB_XINPUT_LD = XCB
QMAKE_LIBS_XCB_XINPUT = /usr/lib/arm-linux-gnueabihf/libxcb-xinput.so
QMAKE_DEPENDS_XCB_XKB_CC = XCB
QMAKE_DEPENDS_XCB_XKB_LD = XCB
QMAKE_LIBS_XCB_XKB = /usr/lib/arm-linux-gnueabihf/libxcb-xkb.so
QMAKE_LIBS_XKBCOMMON_X11 = /usr/lib/arm-linux-gnueabihf/libxkbcommon-x11.so /usr/lib/arm-linux-gnueabihf/libxkbcommon.so
