QT.widgets_private.VERSION = 5.12.8
QT.widgets_private.name = QtWidgets
QT.widgets_private.module =
QT.widgets_private.libs = $$QT_MODULE_LIB_BASE
QT.widgets_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWidgets/5.12.8 $$QT_MODULE_INCLUDE_BASE/QtWidgets/5.12.8/QtWidgets
QT.widgets_private.frameworks =
QT.widgets_private.depends = core_private gui_private widgets
QT.widgets_private.uses =
QT.widgets_private.module_config = v2 internal_module
QT.widgets_private.enabled_features = widgettextcontrol effects gtk3 style-fusion style-windows
QT.widgets_private.disabled_features = style-android style-mac style-windowsvista
QMAKE_LIBS_GTK3 = /usr/lib/arm-linux-gnueabihf/libgtk-3.so /usr/lib/arm-linux-gnueabihf/libgdk-3.so /usr/lib/arm-linux-gnueabihf/libpangocairo-1.0.so /usr/lib/arm-linux-gnueabihf/libpango-1.0.so /usr/lib/arm-linux-gnueabihf/libharfbuzz.so /usr/lib/arm-linux-gnueabihf/libatk-1.0.so /usr/lib/arm-linux-gnueabihf/libcairo-gobject.so /usr/lib/arm-linux-gnueabihf/libcairo.so /usr/lib/arm-linux-gnueabihf/libgdk_pixbuf-2.0.so /usr/lib/arm-linux-gnueabihf/libgio-2.0.so /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so /usr/lib/arm-linux-gnueabihf/libglib-2.0.so
QMAKE_INCDIR_GTK3 = /usr/include/gtk-3.0 /usr/include/at-spi2-atk/2.0 /usr/include/at-spi-2.0 /usr/include/dbus-1.0 /usr/lib/arm-linux-gnueabihf/dbus-1.0/include /usr/include/gtk-3.0 /usr/include/gio-unix-2.0 /usr/include/cairo /usr/include/pango-1.0 /usr/include/fribidi /usr/include/harfbuzz /usr/include/atk-1.0 /usr/include/cairo /usr/include/pixman-1 /usr/include/uuid /usr/include/freetype2 /usr/include/libpng16 /usr/include/gdk-pixbuf-2.0 /usr/include/libmount /usr/include/blkid /usr/include/glib-2.0 /usr/lib/arm-linux-gnueabihf/glib-2.0/include
